use rapidhash_core::{resolve_manifest_path, AlgorithmId};
use rapidhash_formats::{
    format_gnu_manifest, format_sfv_manifest, parse_gnu_manifest, parse_sfv_manifest, FormatError,
};
use std::path::Path;

#[test]
fn parse_and_format_gnu_canonical() {
    let manifest_text = r#"
# SHA256 test manifest
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  empty.txt
ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad  subdir/abc.txt
"#;

    let entries = parse_gnu_manifest(manifest_text, Some(AlgorithmId::Sha256))
        .expect("should parse canonical GNU manifest");

    assert_eq!(entries.len(), 2);
    assert_eq!(entries[0].path_str, "empty.txt");
    assert_eq!(entries[0].line_number, 3);
    assert_eq!(
        entries[0].digest.to_hex_lowercase(),
        "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
    );

    assert_eq!(entries[1].path_str, "subdir/abc.txt");
    assert_eq!(entries[1].line_number, 4);

    let formatted = format_gnu_manifest(&entries);
    assert!(formatted
        .contains("e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  empty.txt\n"));
    assert!(formatted.contains(
        "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad  subdir/abc.txt\n"
    ));
}

#[test]
fn parse_gnu_binary_mode_marker() {
    let manifest_text =
        "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad *binary_file.bin\n";
    let entries = parse_gnu_manifest(manifest_text, None).expect("should parse binary marker");
    assert_eq!(entries.len(), 1);
    assert_eq!(entries[0].path_str, "binary_file.bin");
}

#[test]
fn parse_gnu_handles_spaces_in_path() {
    let manifest_text = "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad  path with multiple spaces.iso\n";
    let entries = parse_gnu_manifest(manifest_text, None).expect("should parse path with spaces");
    assert_eq!(entries.len(), 1);
    assert_eq!(entries[0].path_str, "path with multiple spaces.iso");
}

#[test]
fn parse_and_format_sfv_with_spaces_and_comments() {
    let sfv_text = r#"
; Generated by test suite
; Another comment line
file_with_spaces in name.zip CBF43926
nested/file.bin 00000000
"#;

    let entries = parse_sfv_manifest(sfv_text).expect("should parse SFV manifest");
    assert_eq!(entries.len(), 2);
    assert_eq!(entries[0].path_str, "file_with_spaces in name.zip");
    assert_eq!(entries[0].digest.to_hex_uppercase(), "CBF43926");
    assert_eq!(entries[0].line_number, 4);

    assert_eq!(entries[1].path_str, "nested/file.bin");
    assert_eq!(entries[1].digest.to_hex_uppercase(), "00000000");
    assert_eq!(entries[1].line_number, 5);

    let formatted = format_sfv_manifest(&entries, Some("Custom comment"));
    assert!(formatted.starts_with("; Custom comment\n"));
    assert!(formatted.contains("file_with_spaces in name.zip CBF43926\n"));
    assert!(formatted.contains("nested/file.bin 00000000\n"));
}

#[test]
fn sfv_rejects_invalid_crc_length() {
    let invalid_sfv = "bad_file.zip 1234\n";
    let err = parse_sfv_manifest(invalid_sfv);
    assert!(matches!(err, Err(FormatError::InvalidSyntax { .. })));
}

#[test]
fn gnu_rejects_malformed_lines() {
    let malformed = "just_a_single_word\n";
    let err = parse_gnu_manifest(malformed, None);
    assert!(matches!(err, Err(FormatError::InvalidSyntax { .. })));
}

#[test]
fn manifest_entries_safely_confine_against_approved_root() {
    let manifest_text = r#"
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  valid/relative/path.txt
ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad  ../escape_attempt.txt
"#;

    let entries = parse_gnu_manifest(manifest_text, Some(AlgorithmId::Sha256))
        .expect("manifest syntax itself is parseable");

    let root = Path::new(if cfg!(windows) {
        r"C:\app\root"
    } else {
        "/app/root"
    });

    // First entry resolves safely
    let resolved = resolve_manifest_path(root, &entries[0].path_str);
    assert!(resolved.is_ok());

    // Second entry attempts path traversal escape and is blocked by path_policy
    let escaped = resolve_manifest_path(root, &entries[1].path_str);
    assert!(escaped.is_err());
}
