//! SFV (Simple File Verification) manifest parsing and formatting.
//!
//! Implements Section 4 of CHECKSUM_FORMATS.md:
//! Blank lines and lines beginning with a semicolon are comments.
//! A data line ends with an eight-digit CRC32 value separated from the file name
//! by whitespace. Parsing proceeds from the digest at the end so spaces in
//! file names remain representable. Generated CRC values use uppercase hexadecimal.

use crate::entry::ManifestEntry;
use crate::error::FormatError;
use rapidhash_core::{AlgorithmId, Digest};

/// Parse an SFV manifest string into a list of entries.
pub fn parse_sfv_manifest(content: &str) -> Result<Vec<ManifestEntry>, FormatError> {
    let mut entries = Vec::new();

    for (idx, raw_line) in content.lines().enumerate() {
        let line_number = idx + 1;
        let line = raw_line.trim_end_matches(['\r', '\n']);
        let trimmed = line.trim();

        // Skip blank lines and semicolon comments
        if trimmed.is_empty() || trimmed.starts_with(';') {
            continue;
        }

        // Parse from the right: the last whitespace-delimited token must be an 8-char hex CRC
        let last_space_idx = match line.rfind(|c: char| c.is_ascii_whitespace()) {
            Some(idx) => idx,
            None => {
                return Err(FormatError::InvalidSyntax {
                    line: line_number,
                    reason: "SFV line missing separating whitespace between filename and CRC32"
                        .to_string(),
                });
            }
        };

        let path_part = line[..last_space_idx].trim_end();
        let hex_part = line[last_space_idx..].trim();

        if path_part.is_empty() || hex_part.is_empty() {
            return Err(FormatError::InvalidSyntax {
                line: line_number,
                reason: "SFV line must contain both filename and CRC32 digest".to_string(),
            });
        }

        if hex_part.len() != 8 {
            return Err(FormatError::InvalidSyntax {
                line: line_number,
                reason: format!(
                    "SFV CRC32 must be exactly 8 hex characters, found {}",
                    hex_part.len()
                ),
            });
        }

        let digest = Digest::from_hex(AlgorithmId::Crc32, hex_part).map_err(|err| {
            FormatError::InvalidSyntax {
                line: line_number,
                reason: format!("malformed CRC32 digest '{hex_part}': {err}"),
            }
        })?;

        entries.push(ManifestEntry::new(path_part, digest, line_number));
    }

    Ok(entries)
}

/// Format a list of manifest entries into an SFV manifest string.
///
/// Uses uppercase hexadecimal for CRC32 values according to specification Section 4.
pub fn format_sfv_manifest(entries: &[ManifestEntry], comment_header: Option<&str>) -> String {
    let mut output = String::new();
    if let Some(header) = comment_header {
        for line in header.lines() {
            output.push_str("; ");
            output.push_str(line);
            output.push('\n');
        }
    } else {
        output.push_str("; Generated by RapidHash\n");
    }

    for entry in entries {
        output.push_str(&entry.path_str);
        output.push(' ');
        output.push_str(&entry.digest.to_hex_uppercase());
        output.push('\n');
    }
    output
}
